all:
	clang -I../../include  -o ../../bin/testAudio testAudio.c `sdl-config --cflags --libs`  ../../lib/libAlcubierre.a -lm
	clang -I../../include  -o ../../bin/testDubstep dubstep.c `sdl-config --cflags --libs` ../../lib/libAlcubierre.a -lm
	
